language: node_js
node_js:
 — “6.9.4”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project 
github-travis-firebase-tut- — token $FIREBASE_TOKEN