language: node_js
node_js:
  - "6.9.4"
cache:
  directories:
    - "node_modules"
script:
  - echo "Deploying!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy — project github-travis-firebase-tut — token $FIREBASE_TOKEN.