language: node_js
node_js:
  - "6.9.4"
cache:
  directories:
    - "node_modules"
script:
  - echo "Deploying!!"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "github-travis-firebase-tut"

