language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - echo "Deploying!!"
branches:
  only:
  - master
before_install:
  - npm install -g firebase-tools
install:
  - npm install
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

